export const loremIpsum = `Lorem ipsum odor amet, consectetuer adipiscing elit. Posuere sem vulputate ultrices, feugiat amet vivamus. Diam enim ultricies congue; elit platea curabitur platea. Fringilla ultricies sagittis, nisl ipsum nunc malesuada. Ligula iaculis commodo curae dui urna nec eros elit. Tincidunt tempus justo conubia, elit mollis natoque cursus. Pretium lacinia faucibus platea facilisis dui. Diam nam nisi mauris ipsum diam pulvinar. Curabitur interdum ex ultricies platea sem convallis finibus!

Sapien ad nascetur tincidunt placerat fames feugiat. Nullam quam interdum hendrerit eros amet consectetur penatibus phasellus. Molestie per consequat curabitur duis vitae mattis. Consectetur efficitur erat venenatis platea orci quis vel. Phasellus lectus egestas in tristique quis semper eleifend. Sagittis et blandit nunc montes congue ligula rhoncus sit vulputate. Curae ultrices consequat aliquam tellus est torquent? Fames integer porttitor id ac porttitor sociosqu lobortis eleifend. Facilisis eros semper fringilla enim finibus tellus mus interdum pharetra.

Diam aliquam pretium dolor nunc dis eros consequat sit. Ultrices sem non luctus placerat; rutrum nibh sapien. Massa hac luctus ultrices tincidunt habitant mauris blandit eu. Lobortis aptent dictum maximus scelerisque auctor egestas ultrices. Senectus eget ullamcorper tempor eget vestibulum. Ante elit mattis ut suspendisse tellus sodales feugiat. Class primis convallis montes mus nibh tincidunt nec nascetur penatibus. Sollicitudin sagittis hac nam erat dui. Urna dolor auctor; torquent accumsan montes in ac gravida dictum.

Sapien commodo ad aptent efficitur ut lectus amet integer. Volutpat ac iaculis consequat libero sem ultrices integer? Sagittis luctus massa tellus aliquam mi curae curae. Est convallis ornare suscipit hendrerit vehicula aenean. Nascetur tellus facilisi quis turpis nostra fermentum. Elit convallis porttitor pulvinar suscipit mus sodales congue pulvinar urna. Malesuada consectetur volutpat efficitur ligula sit dui ex. Ex himenaeos massa dapibus nibh; imperdiet ornare ac. Congue consectetur turpis fusce imperdiet; commodo integer quam purus.

Per etiam dolor semper rutrum eu egestas penatibus. Luctus interdum pretium vitae eu mollis finibus fames. Ultricies eleifend sit feugiat convallis, fermentum morbi quisque. Viverra placerat turpis aliquet sociosqu semper. Ultrices non nisl dictum consectetur sit sociosqu dis habitant. Sagittis dictum rutrum neque consequat himenaeos.`;
